# The N-Dimensional Array

What is an example of a real life 1-d, 2-d, 3-d, 4-d array?

So far we've talked about the one dimensional array.
Lets review quickly.

In [2]:
import numpy as np
#Again, all examples will be on np.arange(10)
arr = np.arange(10)

In [2]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Things we can do with a 1-d array

### 1: Operations with a scalar

In [3]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### 2: Operations with another 1-d array

In [4]:
arr2 = np.arange(10,20)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [5]:
arr + arr2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

### 3: Certain Mathematical Operations

In [6]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

### 4: Summary Operations

In [7]:
arr.mean()

4.5

In [8]:
arr.max()

9

In [9]:
#Location analog

arr.argmax()

9

### 5: Information Operations

In [10]:
len(arr)

10

In [11]:
#Kind of odd
arr.shape

(10,)

In [12]:
#Total number of elements
arr.size

10

In [13]:
arr.ndim

1

### 6: Comparison Operations (With a scalar or another 1-d array)

In [14]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr > 0

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [16]:
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
arr > arr2

array([False, False, False, False, False, False, False, False, False,
       False])

### 7: Special Boolean Operators

In [18]:
bool_arr1 = np.random.randint(0,1+1,10).astype(bool)
bool_arr2 = np.random.randint(0,1+1,10).astype(bool)

In [19]:
bool_arr1

array([ True, False,  True, False,  True, False,  True, False, False,
        True])

In [20]:
bool_arr2

array([False, False,  True, False,  True, False, False, False,  True,
       False])

In [21]:
#and
bool_arr1 & bool_arr2

array([False, False,  True, False,  True, False, False, False, False,
       False])

In [22]:
#or
bool_arr1 | bool_arr2

array([ True, False,  True, False,  True, False,  True, False,  True,
        True])

In [23]:
bool_arr1.any()

True

In [24]:
bool_arr1.all()

False

In [25]:
bool_arr1.sum()

5

In [26]:
bool_arr1.mean()

0.5

# Indexing A 1-d Array

### 1: Slicing

In [27]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr[1:-1:3]

array([1, 4, 7])

### What if you use a negative number as a step size?

In [31]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
#reverses it

### 2: Logical Indexing

In [32]:
arr[arr < 3]

array([0, 1, 2])

### 3: Fancy Indexing

In [33]:
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
arr2[[1,5,3]]

array([11, 15, 13])

# Adding Elements to a 1-d Array

For python lists with size flexibility this is easy

In [35]:
lst = [1,2,3]
lst.append(7)
lst

[1, 2, 3, 7]

In [36]:
arr = np.arange(1,4)
arr.append(7)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

### There are two ways to do this

### 1: Cast to list, append/extend, and then cast back to array

In [37]:
#convert to list
list(arr)

[1, 2, 3]

In [38]:
#add 7
list(arr) + [7]

[1, 2, 3, 7]

In [39]:
#convert back to numpy array
np.array(list(arr) + [7])

array([1, 2, 3, 7])

In [40]:
arr = np.array(list(arr) + [7])



### 2: `np.concatenate`

In [41]:
arr = np.arange(1,4)
arr

array([1, 2, 3])

In [44]:
#Need to give command a tuple of arrays/lists
np.concatenate((arr,[7],[34,90]))

array([ 1,  2,  3,  7, 34, 90])

In [45]:
arr = np.concatenate((arr,[7]))

### Speed test

In [46]:
%%timeit
arr2 = np.array(list(arr) + [7])

2.58 µs ± 4.85 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [47]:
%%timeit
arr2 = np.concatenate((arr,[7]))

1.56 µs ± 4.12 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## `np.concatenate` is faster. In general, if you need a lot of size flexibility, numpy may not be right for the task.

# The n-d array

Lets first look at a 2 dimensional array

In [48]:
#Here is H_sym from HW_2 but much smaller
H = np.random.randint(-2000,2000,size=(5,5))
H_sym = (H + H.T)/2

In [49]:
H_sym

array([[  858. ,   293. ,    59. ,  1582. ,  1084. ],
       [  293. , -1163. ,  -765.5,  -138. ,  -838. ],
       [   59. ,  -765.5,   351. , -1719.5,  1442. ],
       [ 1582. ,  -138. , -1719.5,  1787. ,    44. ],
       [ 1084. ,  -838. ,  1442. ,    44. ,  -839. ]])

A 2-d array is a matrix.

What might a 3-d array look like?

https://alexisalulemacom.files.wordpress.com/2017/10/order-3-tensor.png

As we cannot visualize past 3 dimensions lets not worry about a 4-d array

# How to create an N-d array?

In [50]:
#A tuple is a list that cannot be modified
size_tup = (3,3)
size_tup

(3, 3)

In [52]:
np.empty((3,4,5))

array([[[4.94065646e-324, 6.92916506e-310, 1.30589376e-316,
         6.92928086e-310, 4.94065646e-324],
        [4.94065646e-324, 4.94065646e-324, 1.30590601e-316,
         1.48219694e-323, 1.30590009e-316],
        [1.30590206e-316, 1.30590404e-316, 8.39911598e-323,
         4.70329942e-317, 8.39911598e-323],
        [4.70329942e-317, 2.12199579e-313, 8.39911598e-323,
         4.70331523e-317, 6.92916506e-310]],

       [[4.70331523e-317, 2.54639495e-313, 8.39911598e-323,
         4.70333104e-317, 8.39911598e-323],
        [4.70333104e-317, 2.97079411e-313, 1.18575755e-322,
         6.92925947e-310, 4.94065646e-324],
        [1.30589930e-316, 2.12199579e-313, 0.00000000e+000,
         0.00000000e+000, 7.90505033e-323],
        [1.30589574e-316, 1.30589771e-316, 1.30590799e-316,
         4.94065646e-324, 1.08694442e-322]],

       [[1.30590878e-316, 4.94065646e-324, 0.00000000e+000,
         4.94065646e-324, 1.77863633e-321],
        [4.94065646e-324, 6.92916506e-310, 1.30589297e-316,


# What did this do?

In [ ]:
#How to create a 3-d array with sizes 2,5,9?

In [53]:
#How to create a 2-by-7 matrix full of ones?
np.ones((2,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [54]:
#With zeros?
np.zeros((2,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

We cannot use the `arange` command for n-d arrays.

## From a nested list (i.e. list of list or list of lists of lists, etc)

In [55]:
LoL = [[1,2,3],
       [4,5,6],
       [7,8,9]]

LoL

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [56]:
np.array(LoL)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Information Operators on n-d arrays

In [57]:
mat = np.ones((2,7))
mat

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [58]:
mat.shape

(2, 7)

In [59]:
mat.size

14

In [ ]:
#Same as
np.array(mat.shape)

In [60]:
np.array(mat.shape).prod()

14

In [61]:
mat.ndim

2

In [62]:
#same as
len(mat.shape)

2

In [63]:
len(mat)

2

In [64]:
#Same as
mat.shape[0]

2

# Things that are the same as for 1-d arrays

### Operations with a scalar

In [65]:
mat = np.eye(5)
mat

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#What did the eye command do?

In [66]:
mat + 1

array([[2., 1., 1., 1., 1.],
       [1., 2., 1., 1., 1.],
       [1., 1., 2., 1., 1.],
       [1., 1., 1., 2., 1.],
       [1., 1., 1., 1., 2.]])

In [67]:
2**mat

array([[2., 1., 1., 1., 1.],
       [1., 2., 1., 1., 1.],
       [1., 1., 2., 1., 1.],
       [1., 1., 1., 2., 1.],
       [1., 1., 1., 1., 2.]])

### Operations with an n-d array of the same dimension sizes

In [68]:
mat

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [69]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [70]:
mat + np.ones((5,5))

array([[2., 1., 1., 1., 1.],
       [1., 2., 1., 1., 1.],
       [1., 1., 2., 1., 1.],
       [1., 1., 1., 2., 1.],
       [1., 1., 1., 1., 2.]])

In [ ]:
#Adds elementwise

### Mathematical Operations

In [71]:
np.sin(mat)

array([[0.84147098, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.84147098, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.84147098, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.84147098, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.84147098]])

### Summary Operations (With a twist)

In [72]:
heights = [72,73,69,76]

In [73]:
weights = [170,200,158,180]

In [74]:
#How to make a matrix of heights and weights?
M = np.array([heights,weights])

In [75]:
np.array([heights,weights])

array([[ 72,  73,  69,  76],
       [170, 200, 158, 180]])

In [77]:
friend_matrix = np.array([heights,weights]).T
friend_matrix

array([[ 72, 170],
       [ 73, 200],
       [ 69, 158],
       [ 76, 180]])

In [78]:
#The mean
friend_matrix.mean()



124.75

### This isn't what I want
### How do I just take the mean going through a given dimension?

### This `axis = ` argument

In [79]:
friend_matrix

array([[ 72, 170],
       [ 73, 200],
       [ 69, 158],
       [ 76, 180]])

In [80]:
friend_matrix.mean(axis=0)

array([ 72.5, 177. ])

In [81]:
friend_matrix.mean(axis=1)

array([121. , 136.5, 113.5, 128. ])

In [82]:
friend_matrix.mean(axis=2)

IndexError: tuple index out of range

In [ ]:
#Which did I want

In [87]:
friend_matrix.mean(axis=-2)
#Go along last axis

array([ 72.5, 177. ])

### The same for other summary operations

In [88]:
friend_matrix.max()

200

In [91]:
friend_matrix.max(0)

array([ 76, 200])

### Because of the way python works, in these summary operations work you don't need the `axis=` keyword
### Beware: In other places you may.

In [92]:
friend_matrix

array([[ 72, 170],
       [ 73, 200],
       [ 69, 158],
       [ 76, 180]])

In [93]:
friend_matrix.argmax()

3

In [94]:
friend_matrix.argmax(0)

array([3, 1])

In [ ]:
friend_matrix

# A taste of whats to come
### Why do we use pandas?

Don't worry about taking notes on this

In [95]:
import pandas as pd

friend_frame = pd.DataFrame(friend_matrix,index=['Ian','Fayzan','Alex','Zach'],columns=['Height','Weight'])

In [96]:
friend_frame

Height  Weight
Ian         72     170
Fayzan      73     200
Alex        69     158
Zach        76     180

In [97]:
friend_frame.Weight.mean()

177.0

### Comparison Operators

In [98]:
friend_matrix

array([[ 72, 170],
       [ 73, 200],
       [ 69, 158],
       [ 76, 180]])

In [99]:
friend_matrix > 3

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

### You can do this with another matrix of the same size

### Special Boolean Operators

In [100]:
(friend_matrix > 200) | (friend_matrix < 100)

array([[ True, False],
       [ True, False],
       [ True, False],
       [ True, False]])

In [101]:
friend_matrix%2 == 0

array([[ True,  True],
       [False,  True],
       [False,  True],
       [ True,  True]])

In [102]:
(friend_matrix%2 == 0).any()

True

In [105]:
(friend_matrix%2 == 0).any(0)

array([ True,  True])

#### Similar for `.all`

# Broadcasting

We have seen that mathematical operations work with scalars or arrays of the exact same shape.

Lets consider this example.

In [106]:
friend_matrix

array([[ 72, 170],
       [ 73, 200],
       [ 69, 158],
       [ 76, 180]])

Lets say I want to convert everything in column 1 to cms and column 2 to kgs

To get inches to cm I should multiply all the heights by `2.54`
To get pounds to kg I should multiply all the weights by `0.45`

In [108]:
conversion_array = np.array([2.54,0.45])
conversion_array

array([2.54, 0.45])

In [109]:
friend_matrix * conversion_array

array([[182.88,  76.5 ],
       [185.42,  90.  ],
       [175.26,  71.1 ],
       [193.04,  81.  ]])

# What just happend?
# Broadcasting

In [110]:
conversion_array.shape

(2,)

In [111]:
friend_matrix.shape

(4, 2)

### Numpy checks to see if the size of any of the dimensions of `conversion_array` match those of `friend_matrix`

In [112]:
friend_matrix.shape[1]==conversion_array.shape[0]

True

### Numpy then copies `conversion_array` in the other dimension(s) until it matches the other dimension(s) of `friend_matrix`

In [113]:
#Don't worry about this notation
temp = np.array([conversion_array for i in range(4)])

In [114]:
temp

array([[2.54, 0.45],
       [2.54, 0.45],
       [2.54, 0.45],
       [2.54, 0.45]])

In [116]:
friend_matrix

array([[ 72, 170],
       [ 73, 200],
       [ 69, 158],
       [ 76, 180]])

### Note: This is also whats going on when you do operations with a scalar

### Lets do another quick example

In [117]:
friend_matrix + np.array([1,2,3,4])

#What will happen?

ValueError: operands could not be broadcast together with shapes (4,2) (4,) 

### For whatever reason, this does not work

### We must talk about adding dimensions
### This is one of the most unintuitive things about numpy

In [118]:
friend_matrix.shape

(4, 2)

In [119]:
arr = np.array([1,2,3,4])
arr.shape

(4,)

In [120]:
arr[None].shape

(1, 4)

In [134]:
example_matrix = friend_matrix[:2]
add_vec = np.array([3,4])
example_matrix

array([[ 72, 170],
       [ 73, 200]])

In [136]:
#arr[None,:,None].shape
example_matrix.shape
add_vec[:,None] + example_matrix

array([[ 75, 173],
       [ 77, 204]])

In [144]:
arr[None,:,None,None].shape

(1, 4, 1, 1)

### Why did the previous one work without padding dimensions?

I believe numpy allows broadcasting without matching dimensions if you're going to broadcast with the last dimension matching.

If we wanted to be safe we could have done:

In [ ]:
friend_matrix.shape

In [ ]:
conversion_array.shape

In [ ]:
conversion_array[None].shape

In [ ]:
friend_matrix*conversion_array[None]

### This can extend past 1 and 2 dimensional arrays

In [146]:
mat = np.ones((3,4,5))
mat
mat.shape

(3, 4, 5)

In [148]:
np.arange(1,4)
arr = np.arange(1,4)
arr.shape

(3,)

In [152]:
mat + np.arange(1,4)[:,None,None]

array([[[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]],

       [[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]]])

In [150]:
mat.shape

(3, 4, 5)

In [151]:
arr.shape

(3,)

In [153]:
mat2 = np.ones((3,5))
mat2.shape

(3, 5)

In [156]:
#mat + mat2
mat.shape

(3, 4, 5)

In [157]:
mat2[:,None,:].shape

(3, 1, 5)

In [158]:
mat + mat2[:,None,:]

array([[[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]])

### Note: You can skip any trailing colons

In [159]:
mat2[:,None,:]

array([[[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]]])

In [160]:
mat2[:, None]

array([[[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]]])

In [161]:
mat + mat2[:,None]

array([[[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]])

### Final Note About Broadcasting

In [162]:
mat = np.eye(4)

In [163]:
mat.shape
#We have two dimensions both of size 4

(4, 4)

In [164]:
add_arr = np.array([1,2,3,4])

In [165]:
mat + add_arr[None]

array([[2., 2., 3., 4.],
       [1., 3., 3., 4.],
       [1., 2., 4., 4.],
       [1., 2., 3., 5.]])

In [166]:
mat + add_arr[:,None]

array([[2., 1., 1., 1.],
       [2., 3., 2., 2.],
       [3., 3., 4., 3.],
       [4., 4., 4., 5.]])

In [ ]:
#These two are different. Ponder that a bit.

In [167]:
add_arr[None].shape

(1, 4)

In [168]:
add_arr[:,None].shape

(4, 1)

### Adendum

You may see `np.newaxis` in place of `None` in documentation. Both do the same thing. I like `None` because it is faster to write

In [169]:
add_arr[np.newaxis]

array([[1, 2, 3, 4]])

In [170]:
add_arr[None]

array([[1, 2, 3, 4]])

In [1]:
add_arr

NameError: name 'add_arr' is not defined