# Indexing the N-d Array

In [1]:
import numpy as np

In [2]:
heights = [72,73,69,76]
weights = [170,200,158,180]
friend_matrix = np.array([heights,weights]).T

In [3]:
friend_matrix

array([[ 72, 170],
       [ 73, 200],
       [ 69, 158],
       [ 76, 180]])

### Single Element Selection

In [4]:
#How to select 170?
friend_matrix[0,1]

#Row 0, element 1

170

In [5]:
#How do we select 76?
friend_matrix[3,0]

76

### You can imagine how this would extend past 2 dimensions

# Lets talk about our 2 ways of indexing

# 1: Slicing

In [6]:
friend_matrix

array([[ 72, 170],
       [ 73, 200],
       [ 69, 158],
       [ 76, 180]])

In [7]:
#How would we select only the 1st row? (As in row 0)
friend_matrix[0,:]

#What do I put where the question mark is?

array([ 72, 170])

In [8]:
#How about the first column?
friend_matrix[:,0]

array([72, 73, 69, 76])

### Note: Trailing colons can be left out

In [9]:
friend_matrix[0,:]

array([ 72, 170])

In [10]:
friend_matrix[0]

array([ 72, 170])

In [12]:
#How would we select 0 to 2 from the second column?
friend_matrix[0:3,1]

array([170, 200, 158])

### Operations via slicing

In [17]:
#Double the 3rd row?
friend_matrix
friend_matrix[2,:]*=2
friend_matrix

array([[ 72, 170],
       [ 73, 200],
       [276, 632],
       [ 76, 180]])

In [18]:
#Take the mean of the 2nd column?
friend_matrix[:,1].mean()

295.5

### Warning: Be careful about slicing and broadcasting

In [21]:
friend_matrix[:,0].shape

(4,)

In [22]:

friend_matrix
friend_matrix*friend_matrix[:,0]

ValueError: operands could not be broadcast together with shapes (4,2) (4,) 

### Note: You may deal with this on your hw

In [26]:
#How would we fix this?
friend_matrix[:,0][:,None]*friend_matrix

array([[  5184,  12240],
       [  5329,  14600],
       [ 76176, 174432],
       [  5776,  13680]])

### Another way:

In [31]:
friend_matrix[:,0:1]

array([[ 72],
       [ 73],
       [276],
       [ 76]])

In [32]:
#This keeps it in the proper format
friend_matrix[:,0:1].shape

(4, 1)

In [ ]:
friend_matrix[:,1:]

### The `<STEP>` argument in slicing

## How would we select every other column?

In [33]:
friend_matrix[:,::2]

array([[ 72],
       [ 73],
       [276],
       [ 76]])

## How would we reverse the order of the columns?

In [34]:
friend_matrix[:,::-1]

array([[170,  72],
       [200,  73],
       [632, 276],
       [180,  76]])

# 2: Logical Indexing

In [35]:
friend_matrix

array([[ 72, 170],
       [ 73, 200],
       [276, 632],
       [ 76, 180]])

In [36]:
#How would we select the even elements?
#Same as before
friend_matrix[friend_matrix%2==0]

array([ 72, 170, 200, 276, 632,  76, 180])

In [ ]:
#Returns a 1-d array

### Note: You can chain together with & or | in the same way

### Logical Indexing on Certain Dimensions

In [37]:
friend_matrix

array([[ 72, 170],
       [ 73, 200],
       [276, 632],
       [ 76, 180]])

In [ ]:
#How might we select rows where height is greater than 72?

In [39]:
#First, how would we check that rows have height greater than 72?
friend_matrix[:,0]>72

array([False,  True,  True,  True])

In [ ]:
#1: Select heights















friend_matrix[:,0]

In [40]:
#2: Check if greater than 72












friend_matrix[:,0]>72

array([False,  True,  True,  True])

In [41]:
#3: Exactly what you'd usually do to select certain rows

friend_matrix[friend_matrix[:,0]>72,:]








#friend_matrix[friend_matrix[:,0]>72]

array([[ 73, 200],
       [276, 632],
       [ 76, 180]])

In [ ]:
#How to select columns that contain a number divisible by 5?

In [48]:
#1: Select the columns that have a number divisible by 5
#Hint: use np.any()
(friend_matrix%5==0).any(0)

array([False,  True])

In [44]:
#2: Exactly what you'd usually do to select certain columns
friend_matrix[:,(friend_matrix%5==0).any(0)]

array([[170],
       [200],
       [632],
       [180]])

### Note: You can use logicial indexing on multiple dimensions at once

In [45]:
friend_matrix

array([[ 72, 170],
       [ 73, 200],
       [276, 632],
       [ 76, 180]])

In [46]:
#Lets select rows where height is greater than 72 and columns that have a number divisible by 5
friend_matrix[friend_matrix[:,0]>72,(friend_matrix%5==0).any(0)]

array([200, 632, 180])

### Note: You can combine slicing with logical indexing

In [47]:
#Ex: Select first 2 rows from the columns that have a number divisible by 5?
friend_matrix[:2,(friend_matrix%5==0).any(0)]

array([[170],
       [200]])

### 3: Fancy Indexing

Recall fancy indexing on a 1-d array

Similar on n-d arrays, I never use it so feel free to play with it on your own