In [1]:
import numpy as np
import numpy.linalg as la

# Linear Independence

In [2]:
data = np.array([[710,720,1430],[650,800,1450],[730,640,1370],[800,770,1570],[690,710,1400]])

In [3]:
data

array([[ 710,  720, 1430],
       [ 650,  800, 1450],
       [ 730,  640, 1370],
       [ 800,  770, 1570],
       [ 690,  710, 1400]])

In [4]:
la.matrix_rank(data)
#Tells us there are only 2 linearly independent columns
#Worthless to have column 3 if we were to do some statistical test, it provides us no new information.
#In reality any 2 of the 3 is good

2

# Linear Regression

In [5]:
#remove 3rd column
A = data[:,0:2]

In [6]:
y = [85,50,87,100,70]

In [7]:
def linear_regression(A,y):
    #solve A.T A x = A.T y
    x = la.pinv(A.T @ (A)) @ (A.T) @ (y)
    #pinv essentially does SVD
    return x

In [8]:
x_hat = linear_regression(A,y)
print(x_hat)

#What kind of test was this?

[ 0.24623299 -0.1342156 ]


In [9]:
#predictions
A @ x_hat

array([78.19019037, 52.67896359, 93.85209774, 93.64037923, 74.60768662])

In [10]:
#How far off are we?
#Remember vectorization
(A @ x_hat) - y

array([-6.80980963,  2.67896359,  6.85209774, -6.35962077,  4.60768662])

In [11]:
#Lets check magnitude
np.abs((A @ x_hat) - y)

array([6.80980963, 2.67896359, 6.85209774, 6.35962077, 4.60768662])

In [12]:
#Now mean
np.abs((A @ x_hat) - y).mean()

5.4616356708840215

In [13]:
#What if we don't remove the last column
x_hat = linear_regression(data,y)

In [14]:
#Exactly the same error
np.abs((data @ x_hat) - y).mean()

5.461635670884126

In [15]:
#3rd Feature is barely used
x_hat

array([ 0.20889386, -0.17155473,  0.03733913])

### In real datasets without dumb things like this you won't see linearly independent data, but you will see highly correlated data which causes trouble but wastes. 

### We will talk about ways to compress your data to only keep whats useful in the 3rd week. Called "dimensionality reduction"

# Neural Net
Lets create that neural net from the slides with random weights

In [16]:
def ReLU(z):
    z_cop = z.copy()
    z_cop[z_cop<0] = 0
    return z_cop

In [17]:
A

array([[710, 720],
       [650, 800],
       [730, 640],
       [800, 770],
       [690, 710]])

In [18]:
W1 = np.random.randn(2,5)
W2 = np.random.randn(5,7)
W0 = np.random.randn(7,1)

In [19]:
def neural_net(A,W1,W2,W0):
    H_1 = ReLU(A@W1)
    H_2 = ReLU(H_1@W2)
    output = H_2 @ W0
    return output

In [20]:
#Really bad, don't need to check mean error to confirm that, but this is because we haven't updated our random weights
neural_net(A,W1,W2,W0)
#This isn't a task for a neural network

array([[ -960.15417986],
       [ -860.63848325],
       [-1000.28442209],
       [-1087.24800531],
       [ -931.76614205]])