## This lecture is all about indexing 1-d arrays

What is indexing?
    * Selecting elements from arrays
    * We can modify certain elements this way
    * We can create sub-arrays this way

In [1]:
import numpy as np

## Selecting 1 element

In [3]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#If we want to select 3rd element
arr[2]
#3-1

2

In [5]:
#If we want to select the last element
arr[-1]

9

In [6]:
#Second to last element
arr[-2]

8

## Modification

In [7]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr[2] = 3
print(arr)
#modified

[0 1 3 3 4 5 6 7 8 9]


In [10]:
cop = arr[0]

In [11]:
cop = 3
print(arr)
#not modified

[0 1 3 3 4 5 6 7 8 9]


## 1: Slicing

In [13]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#selecting multiple elements

In [16]:
#Select the 3rd to 5th element
arr[2:5]
#<START> to <END> where start inclusive and end exclusive
#What does that mean?

array([2, 3, 4])

In [18]:
#Select 3rd to the second to last element?
#How do you think we would do this?
arr[2:-1]

array([2, 3, 4, 5, 6, 7, 8])

In [19]:
#How to do the 3rd until the last element
arr[2:]
#We put nothing on the other side of the colon
#There is an implied <GO UNTIL THE END> there

array([2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
#How do you think you can do the 1st element to the 7th element?
#There are two ways
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [23]:
#How about slicing the entire array?
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Modification

Similar to how arrays could be operated on by scalars or arrays with the same sizes, modification can be done with scalar or an array the same size as the slice

In [25]:
arr[:3]

array([0, 1, 2])

In [26]:
#With a scalar
arr[:3] = 3
print(arr)
#What will this output look like

[3 3 3 3 4 5 6 7 8 9]


In [27]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
cop = arr[:3]
cop = 3
#What will happen
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
#Replace with an array
arr = np.arange(10)
print(arr)
arr[:3]

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2])

In [33]:
arr[:3] = np.array([11,13,17])
print(arr)

[11 13 17  3  4  5  6  7  8  9]


### Note: Array must be same size as the slice

In [34]:
#Replacing with a list is fine too
arr = np.arange(10)
print(arr)
arr[:3] = [11,13,17]
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[11 13 17  3  4  5  6  7  8  9]


In [40]:
#Operations on slices
arr = np.arange(10)
#Select and double the last 5

#Select the last 5
arr[-5:]*=2
#How?

In [41]:
#double the last 5
#How?
arr

array([ 0,  1,  2,  3,  4, 10, 12, 14, 16, 18])

In [42]:
#You can do similar with mathematical functions
#Ex: apply cosine to last 5
arr[-5:] = np.cos(arr[-5:])



## Fancy Slicing

We've been doing `arr[<START>,<STOP>]` but there is a third argument

(Start being inclusive, stop being exclusive)

In [44]:
arr = np.arange(10)
print(arr[1:-1])

[1 2 3 4 5 6 7 8]


In [45]:
arr[1:-1:2]

array([1, 3, 5, 7])

`arr[<START>,<STOP>,<STEP>]`

so `arr[1:-1:2]` takes every other entry from 2nd to 2nd to last

In [46]:
#What if we want to take every other entry from the whole array?
#Thoughts?
arr[::2]







array([0, 2, 4, 6, 8])

Note: You can modify in this way. For example, double every other entry

In [50]:
arr = np.arange(10)
arr[::2]= arr[::2]/2
print(arr)

[0 1 1 3 2 5 3 7 4 9]


## 2: Logical Indexing

In [51]:
arr = np.arange(4)
arr

array([0, 1, 2, 3])

In [52]:
bool_arr = np.array([False,False,True,True])


In [53]:
arr[bool_arr]
#Only selects the trues

array([2, 3])

In general, we don't create our own boolean arrays out of thin air, they come via comparison

In [54]:
#Example, #only take the elements less than 3
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [56]:
bool_arr = arr<3

In [57]:
arr[bool_arr]

array([0, 1, 2])

In [58]:
#We don't even need to do that many steps
#Simply do
arr[arr < 3]

array([0, 1, 2])

You'll do operations like this a lot.

For example, what if for some reason we found out there was an error in our array an all the entries less than 3 were subtracted by 10.

How do we add 10 to all the entries less than 3?

In [ ]:
#How?
arr[arr < 3]+=10

In [61]:
arr

array([10, 11, 12,  3,  4,  5,  6,  7,  8,  9])

In [62]:
#Multiple conditions
#Remember the & and |
#Ex: Select elements greater than 5 and even
#remember to wrap in parenthesis
arr

array([10, 11, 12,  3,  4,  5,  6,  7,  8,  9])

In [63]:
(arr>5)&(arr%2==0)

array([ True, False,  True, False, False, False,  True, False,  True,
       False])

In [66]:
arr[(arr>5)&(arr%2==0)]

array([10, 12,  6,  8])

In [44]:
#How would we select elements greater than 9 or less than 3?



# 3: Fancy Indexing
More useful on n-d arrays

Idea: We can pass in a list of indices to take from our list

In [68]:
arr = np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [71]:
#Lets say we wanted inds 0, 3, and 5
inds = [0,3,5]
arr[[0,3,5]]

array([10, 13, 15])