In [1]:
import numpy as np

## HW_2

#### Exercises (5 Exercises)
In each of these exercises I will ask you to remove the loop(s) from the code.

#### Note: Use numpys built in function to build your initial range arrays

In [2]:
#Exercise 1
#WITH LOOPS
arr = list(range(10))
print(arr)
for i in range(len(arr)):
    arr[i]**=2
print(arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [3]:
#Exercise 1
#WITHOUT LOOPS
arr = np.arange(10)
arr**=2
print(arr)

[ 0  1  4  9 16 25 36 49 64 81]


In [4]:
#Exercise 2
#WITH LOOPS
arr = list(range(10))
bool_arr = []
for ele in arr:
    bool_arr.append(ele != 3)
print(bool_arr)

[True, True, True, False, True, True, True, True, True, True]


In [5]:
#Exercise 2
#WITHOUT LOOPS
arr = np.arange(10)
bool_arr = arr != 3
print(bool_arr)

[ True  True  True False  True  True  True  True  True  True]


In [6]:
#Exercise 3
#WITH LOOPS
arr = list(range(10))
print(arr)
new_arr = []
for ele in arr:
    if ele>=5:
        new_arr.append(ele)
print(new_arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[5, 6, 7, 8, 9]


In [7]:
#Exercise 3
#WITHOUT LOOPS
#NOTE: DO NOT simply do something of the form new_arr = np.arange(5,10)
arr = np.arange(10)
new_arr = arr[arr>5]
print(new_arr)

[6 7 8 9]


In [8]:
#Exercise 4
#WITH LOOPS
arr = list(range(10))
print(arr)
tot = 0
num_els = 0
for ele in arr:
    if ele%2==0:
        tot+=ele
print(tot)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
20


In [9]:
#Exercise 4
#WITHOUT LOOPS
arr = np.arange(10)
tot = arr[arr%2==0].sum()
print(tot)

20


In [10]:
#Exercise 5
#WITH LOOPS
arr = list(range(10))
print(arr)
tot = 0
num_els = 0
for ele in arr:
    if ele%2==0 and ele%3==0:
        tot+=ele
        num_els+=1
print(tot/num_els)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
3.0


In [11]:
#Exercise 5
#WITHOUT LOOPS
#NOTE: No division will be needed
arr = np.arange(10)
print(arr)
print(arr[(arr%2==0) & (arr%3==0)].mean())

[0 1 2 3 4 5 6 7 8 9]
3.0


### Bonus
Write the convexification procedure from class

In [12]:
import numpy as np
import numpy.linalg as la

def convexification(H):
    beta = 1e6
    
    #WRITE CODE HERE
    if np.all(H==0):
        eps = 1
    else:
        eps = la.norm(H)/beta
    
    L, V = la.eig(H)
    L_bar = np.abs(L)
    L_bar[L_bar<eps]=eps
    L_bar_mat = np.diag(L_bar)
    B = V@L_bar_mat@V.T
    return B

In [13]:
#You can test your code for syntax errors on 'H_sym'
H = np.random.randint(-2000,2000,size=(100,100))
H_sym = (H + H.T)/2

In [14]:
#Test this code
test_H = np.diag(np.arange(-2,2))
test_H

array([[-2,  0,  0,  0],
       [ 0, -1,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  1]])

In [15]:
#This is the answer
convexification(test_H)

array([[2.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 2.44948974e-06, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])